language: c

compiler:
  - clang
  - gcc

env:
  - FCPATH="$PWD/majek/fluxcapacitor/fluxcapacitor -o log -vvvv"

branches:
  only:
    - master

install:
  - sudo apt-get -qq -y install nodejs erlang-nox
  - make build

script:
  - make test

after_script:
  - cat log

notifications:
  email:
    recipients:
      - travis@popcount.org
